### ISSUE TITLE
Rename WithoutLabel to WithoutLabelElement and deprecate it

### ISSUE THREAD

**Issue by zabulus** [MRCollective/ChameleonForms#122]
Here is a test in DefaultFieldGeneratorTest that fails:
```C#        
        [Test]
        public void GetLabelHtml_should_not_return_any_string_if_WithoutLabel_used_and_DisplayAttribute_present()
        {
            var generator = Arrange(x => x.StringWithDisplayAttribute);
            var fieldConfig = new FieldConfiguration();
            fieldConfig.WithoutLabel();
            var config = generator.PrepareFieldConfiguration(fieldConfig, FieldParent.Section);
            var actual = generator.GetLabelHtml(config).ToString();
            Assert.That(actual, Is.Empty);
        }
```

**Comment by robdmoore** [comment]
I think this is a misunderstanding maybe? `.WithoutLabel` means don't use the label element rather than don't show a label at all?

**Comment by zabulus** [comment]
Hm that makes sense. Maybe it should be named WithoutLabelTag? Or maybe add clarification to the documentation.
BTW I thought field configuration should specify what generate and not how generate.

**Comment by robdmoore** [comment]
I agree that `WithoutLabel` is misleading. The xmldoc should make it clear what it does.

I'm hesitant to make a breaking rename change because this code is called from razor views which most people don't compile. We could create an alias name that is easier to understand though (but simply calls `WithoutLabel`). We could even mark `WithoutLabel` obsolete so people don't use it from now on?

As to what the method *should* be called. What about `WithoutLabelElement`?

**Comment by zabulus** [comment]
Fix according to last comment
